"""add association table and fix us

Revision ID: 123677f00ab2
Revises: 8858044ebb1b
Create Date: 2025-12-18 02:27:55.576449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123677f00ab2'
down_revision: Union[str, Sequence[str], None] = '8858044ebb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source', 'item_associations', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_target', 'item_associations', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_item_associations_id'), 'item_associations', ['id'], unique=False)
    op.create_index(op.f('ix_item_associations_source_id'), 'item_associations', ['source_id'], unique=False)
    op.create_index(op.f('ix_item_associations_target_id'), 'item_associations', ['target_id'], unique=False)
    op.drop_column('user_stories', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_item_associations_target_id'), table_name='item_associations')
    op.drop_index(op.f('ix_item_associations_source_id'), table_name='item_associations')
    op.drop_index(op.f('ix_item_associations_id'), table_name='item_associations')
    op.drop_index('idx_target', table_name='item_associations')
    op.drop_index('idx_source', table_name='item_associations')
    op.drop_table('item_associations')
    # ### end Alembic commands ###
