"""add reset password fields

Revision ID: d852b5d2ef58
Revises: 82034cc5be51
Create Date: 2025-12-17 03:00:23.596404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd852b5d2ef58'
down_revision: Union[str, Sequence[str], None] = '82034cc5be51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_reset_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_failed_reset_attempt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_failed_reset_attempt')
    op.drop_column('users', 'failed_reset_attempts')
    op.drop_column('users', 'reset_code_expires_at')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
